#!/bin/bash
# =============================================================================
# mrefd container entrypoint.
# Renders /etc/mrefd/mrefd.cfg from the MREFD_* environment variables, verifies
# the live-editable list files exist, and execs mrefd.
# =============================================================================
set -euo pipefail

CFG=/etc/mrefd/mrefd.cfg

die() { echo "entrypoint: ERROR: $*" >&2; exit 1; }
note() { echo "entrypoint: $*" >&2; }

# ---- required fields --------------------------------------------------------
: "${MREFD_CALLSIGN:?MREFD_CALLSIGN is required (e.g. M17-XYZ)}"
: "${MREFD_MODULES:?MREFD_MODULES is required (e.g. BCD)}"
: "${MREFD_COUNTRY:?MREFD_COUNTRY is required (ISO-3166-1 alpha-2, e.g. US)}"
: "${MREFD_EMAIL:?MREFD_EMAIL is required}"
: "${MREFD_DASHBOARD_URL:?MREFD_DASHBOARD_URL is required}"

[[ "$MREFD_CALLSIGN" =~ ^M17-[A-Z0-9]{3}$ ]] || \
    die "MREFD_CALLSIGN must be 'M17-' followed by 3 A-Z/0-9 chars (got '$MREFD_CALLSIGN')"
[[ "$MREFD_MODULES" =~ ^[A-Z]+$ ]] || \
    die "MREFD_MODULES must be uppercase A-Z letters only (got '$MREFD_MODULES')"

# ---- defaults ---------------------------------------------------------------
MREFD_PORT="${MREFD_PORT:-17000}"
MREFD_IPV4_BIND="${MREFD_IPV4_BIND-0.0.0.0}"
MREFD_IPV6_BIND="${MREFD_IPV6_BIND-::}"
MREFD_LISTEN_ONLY_ALLOW_ENCRYPT="${MREFD_LISTEN_ONLY_ALLOW_ENCRYPT:-false}"
MREFD_DHT_ENABLED="${MREFD_DHT_ENABLED:-true}"
MREFD_BOOTSTRAP="${MREFD_BOOTSTRAP:-xrf757.openquad.net}"

# ---- render mrefd.cfg -------------------------------------------------------
{
    echo "# Generated by entrypoint.sh at $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "# Do not edit inside the container - edit .env and restart the service."
    echo
    echo "Callsign = ${MREFD_CALLSIGN}"
    echo "Modules = ${MREFD_MODULES}"
    if [[ -n "${MREFD_ENCRYPTION_ALLOWED:-}" ]]; then
        echo "EncryptionAllowed = ${MREFD_ENCRYPTION_ALLOWED}"
    fi
    echo "ListenOnlyAllowEncrypt = ${MREFD_LISTEN_ONLY_ALLOW_ENCRYPT}"
    echo

    if [[ -n "${MREFD_IPV4_BIND}" ]]; then
        echo "IPv4BindAddr = ${MREFD_IPV4_BIND}"
    fi
    if [[ -n "${MREFD_IPV6_BIND}" ]]; then
        echo "IPv6BindAddr = ${MREFD_IPV6_BIND}"
    fi
    if [[ -z "${MREFD_IPV4_BIND}" && -z "${MREFD_IPV6_BIND}" ]]; then
        die "at least one of MREFD_IPV4_BIND or MREFD_IPV6_BIND must be set"
    fi
    echo "Port = ${MREFD_PORT}"
    echo

    echo "PidPath = /var/run/mrefd/mrefd.pid"
    echo "JsonPath = /var/log/mrefd/mrefd.json"
    echo "WhitelistPath = /etc/mrefd/mrefd.whitelist"
    echo "BlacklistPath = /etc/mrefd/mrefd.blacklist"
    echo "InterlinkPath = /etc/mrefd/mrefd.interlink"
    echo

    if [[ "${MREFD_DHT_ENABLED}" == "true" ]]; then
        [[ -n "${MREFD_IPV4_EXT:-}" ]] && echo "IPv4ExtAddr = ${MREFD_IPV4_EXT}"
        [[ -n "${MREFD_IPV6_EXT:-}" ]] && echo "IPv6ExtAddr = ${MREFD_IPV6_EXT}"
        echo "DashboardURL = ${MREFD_DASHBOARD_URL}"
        echo "EmailAddr = ${MREFD_EMAIL}"
        echo "Bootstrap = ${MREFD_BOOTSTRAP}"
        echo "DHTSavePath = /var/lib/mrefd/mrefd.dht.bin"
        echo "Country = ${MREFD_COUNTRY}"
        if [[ -n "${MREFD_SPONSOR:-}" ]]; then
            [[ "${MREFD_SPONSOR}" == *"="* ]] && \
                die "MREFD_SPONSOR must not contain '=' (got '${MREFD_SPONSOR}')"
            echo "Sponsor = ${MREFD_SPONSOR}"
        fi
    fi
} > "$CFG"

# ---- ensure list files exist ------------------------------------------------
# mrefd requires whitelist/blacklist/interlink files to exist even if empty.
# Users bind-mount /etc/mrefd/config-in on top of individual files; if the
# mounts are missing (fresh deploy), fall back to empty defaults.
for f in mrefd.whitelist mrefd.blacklist mrefd.interlink; do
    if [[ ! -f "/etc/mrefd/${f}" ]]; then
        note "creating empty ${f} (no host mount provided)"
        : > "/etc/mrefd/${f}"
    fi
done

note "starting mrefd as ${MREFD_CALLSIGN} on modules ${MREFD_MODULES}, UDP ${MREFD_PORT}"
exec /usr/local/bin/mrefd "$CFG"
